
> Congrats! 

You have just setup your own Good Governance Initiative dashboard. You may now:

* Start selecting activities from the list and update their progress labels from 'Not Started' to 'In Progress'.
* Visit the [OSPO Alliance](https://ospo.zone) website to know more about the initiative and get the latest news.
* Register on the [mailing list](https://accounts.eclipse.org/mailing-list/ospo.zone) to introduce yourself to the community, and start asking questions!

You can also note these interesting links:
* Communicate this URL to your teams: https://ggi.ow2.io/my-ggi-board-test.
* Communicate this URL to your teams: https://gitlab.ow2.org/ggi/my-ggi-board-test/-/boards.


Note: this message will disappear once you start making progress on tasks.

